services:
  postgres:
    image: postgres:16
    container_name: postgres16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:jbank}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:123}
      POSTGRES_DB: ${POSTGRES_DB:jbankdb}
    ports:
      - "${POSTGRES_PORT:5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pg_data: